[package]
name = "todo-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dirs-next = "2.0.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
